language: java
jdk:
    - oraclejdk9
addons:
  sonarcloud:
    organization: "kuceraf-github" # the key of the org you chose at step #3
    token:
      secure: Tdvfkot3lqMgpHzupapgFWSZEhPRSUfkprjNHVjZyEKKxxiSRf9G6F7xM/B5IV2f/UpPBGBTQEzx2nta+Tk2k64aRNEnc2t8ybLmogv2E3oPeY3Aw0OL2wLk/nQ7v4vZSZP11EfvDYaezP0THRQnaf/G6g8FPCgsgiFHr5eQEroRmzXcbBT0+akRU6SHYkoRQMDa15yecDgHNhVbcHQIIg5ZF9/f0rQI6ffLG+3SkmTCjzY0DWKAO01BJRTux2rYGsHjIPXtqJVmBRHCfd35X+2lVOMapMjZexknkol4BtgGPv/+V2Ebv2ul3rApNBB484d75ZjrPnslmb0rhSAN4n9V1J2Rl6lMnPnOJ28E/EJOHeJfE7ikN1Ro5OyniipopFIZsD0rkYGZ7ceo7yG97Kovg1refxB7dGJFFE5egUeKywPdZLxAEHSdDLx6khW2ltxzQ2dg+YlJFtS5ZMRId0axLeAoowvOsdZDhGd2LkGq0FQEM8OXwXvuAXj6wmIynBM/at5gnb4msrNr6BfVj58/5aznstLKmBWqsZWgXK7J6qPVEiGbjwVi14A2xKL8A898CmQkA92kJGkfHMvSTl4AgvW5QJzk25Ds0Yonb7mGZiBtyrK7Ju5L8f7xD/GdybLmX2RbwEopmpvHOH/9I++SWkfRVBgosQnPbW1KdKc=
install: true
script:
  mvn clean install -Dmaven.javadoc.skip=true
  - sonar-scanner
