language: java
jdk:
    - oraclejdk9
addons:
  sonarcloud:
    organization: "kuceraf-github" # the key of the org you chose at step #3
    token:
      secure: "SHLWg6VndQgPOROAZumkctXxvRTds9sjGr4vwi/d3Kcm82MR5qYdG/HkUD6LU/6+rMXvghyWgZzC67AIIL7hbdgpiVArintZY/w0BgaZsUTrpnQV08qVkOu88e8bgAKRD3sTNZjFsioEj54hFYiItHxb9hiFxmQXLWCSuMyZHTXZPLcBk5nIMGal7hJpMtfLVt/B96rK1DivRvKmeX0+SXf8XKXp3eBnFPzrpk7bThm43W07dd8VzN1vgUq5L4HCW9WGe9f5I2DSYEuPayoc6FF/MqpvbsxxUNHfpmI2qmaKWO+6fM6Vgt5zVCSmz1yzlh66T/prFO5KdDFjWnGa/eWeNFo4OiAxJCDAEPk9AFmjxoLxCT5C4lU5aXllSmi9m0Xf8U/s3xYkHx1qNSTpdxf8HgXyXoqOr3nA6FU1lVPMhclKwJkZAP0+36jCi88HwDeH4cnxPM/+ddWK8ErMdpnVGgDAp4oOKpJj6ycFcfhtBfFR5DoHoDz6SuJ/U0ONgGBzX08nEu7XVjYQSPBc4KScy8tGuH1Iv5Q24bi/I6FflT/OcaXSGpOJnQe0wHijJUxAKY7iJihblafQmhA2lAVyrsZsGCdYEo83mv9Dr3PuGc8+TTqIypQgeJ8TE/+4JZYizN6fgO0tsCW7bmLyah4jhWP89hgjWX/+O9BKL8U="
    branches:
          - master
install: true
script:
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dmaven.javadoc.skip=true
